<option value="what is your childhood nickname">What is your childhood nickname?</option>
<option value="what is the name of your first love">What is the name of your first love?</option>
<option value="name of your favorite childhood teacher">Name of your favorite childhood teacher?</option>
<option value="what is the name of the first school you attended">What is the name of the first school you attended?</option>
<option value="what was your first car">What was your first car?</option>
<option value="what is the name of your favorite childhood friend">What is the name of your favorite childhood friend?</option>
<option value="what street did you live on when you are 12">What street did you live on when you are 12?</option>
<option value="what was your childhood phone number">What was your childhood phone number?</option>
<option value="what is the name of the boy or girl that you first kissed">What is the name of the boy or girl that you first kissed?</option>
<option value="in what city or town was your first job">In what city or town was your first job?</option>
<option value="what is the name of the company of your first job">What is the name of the company of your first job?</option>
<option value="what was the first concert you attended">What was the first concert you attended?</option>
<option value="what is your current car registration number">What is your current car registration number?</option>
<option value="which high school you graduated from">Which High School you graduated from?</option>
<option value="what is your favorite tv program">What is your favorite TV program?</option>
